name: Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.8.1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
